# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
$docker_script = <<SCRIPT
# Get Docker Engine - Community for CentOS
# https://docs.docker.com/install/linux/docker-ce/centos/
sudo yum remove docker \
docker-client \
docker-client-latest \
docker-common \
docker-latest \
docker-latest-logrotate \
docker-logrotate \
docker-engine
sudo yum install -y yum-utils \
device-mapper-persistent-data \
lvm2
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce \
docker-ce-cli \
containerd.io
sudo systemctl enable docker
sudo systemctl start docker && sudo docker --version
sudo groupadd docker # create docker group
sudo usermod -aG docker vagrant # add user to the docker group
sudo docker build -t foremost:latest -<<EOF
FROM ubuntu:19.04
LABEL maintainer="githubfoam "
#ENV PATH /usr/local/bin/foremost:$PATH
RUN apt-get update && \
    apt-get install -y foremost
ENTRYPOINT ["foremost"]
CMD ["--help"]
EOF
sudo docker image ls
SCRIPT
Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-7.6"
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "512"
  end
  config.vm.provision "shell", inline: $docker_script, privileged: false
  config.vm.provision "shell", inline: <<-SHELL
  hostnamectl status
  SHELL
end
