name: "process accounting CI workflow"


on:
  push:
    branches: [ dev ]


jobs:

  ubuntu-latest-job:
    name: "ubuntu-latest - Ubuntu 18.04.5 LTS"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "os fingerprinting"
      run: hostnamectl status  
    - name: "Install process accounting "
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace
        echo "=============process accounting on Linux=============="
        sudo apt-get update -qq
        sudo apt-get install acct -qqy
        whoami #runner
        sudo sa -m # averages for the all the activity for this server overtime        
        # sudo /usr/sbin/accton on
        # sudo dump-acct /var/log/account/pacct | tail
    - name: "Show averages for the all the activity for this server overtime"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace      
        sudo sa -m # averages for the all the activity for this server overtime        
    - name: "Show  sum of the system and user time in cpu minutes for specific commands"
      run: |
        # set -o errexit
        # set -o pipefail
        # set -o nounset
        # set -o xtrace      
        sudo sa -u | grep runner # averages for the all the activity for this server overtime        
        #combined total for a specific user
        #sudo sa -u |grep username|awk ‘BEGIN{TOTAL=0}{TOTAL=TOTAL+$2}END{print TOTAL}’
    - name: "Show each of the programs"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace      
        sudo sa -a       
    - name: " the file in which the data will be saved"
      run: |
        set -o errexit
        set -o pipefail
        set -o nounset
        set -o xtrace      
        ls -lai /var/log/account   
        ls -lai /var/log/account/pacct
        sudo ls -lai /usr/sbin/a*
        sudo dump-acct /var/log/account/pacct | tail
        sudo dump-acct /var/log/account/pacct | tail -5
        sudo dump-acct /var/log/account/pacct | awk -F'|' '$6 ~ / 1000$/'

  # ubuntu-1604-job:
  #   name: "osquery on ubuntu-16.04"
  #   runs-on: ubuntu-16.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install process accounting "
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace
  #       echo "=============process accounting on Linux=============="
  #       sudo apt-get update -qq
  #       sudo apt-get install acct -qqy
  #       whoami #runner
  #       sudo sa -m # averages for the all the activity for this server overtime        
  #       # sudo /usr/sbin/accton on
  #       # sudo dump-acct /var/log/account/pacct | tail
  #   - name: "Show averages for the all the activity for this server overtime"
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace      
  #       sudo sa -m # averages for the all the activity for this server overtime        
  #   - name: "Show  sum of the system and user time in cpu minutes for specific commands"
  #     run: |
  #       # set -o errexit
  #       # set -o pipefail
  #       # set -o nounset
  #       # set -o xtrace      
  #       sudo sa -u | grep runner # averages for the all the activity for this server overtime        
  #       #combined total for a specific user
  #       #sudo sa -u |grep username|awk ‘BEGIN{TOTAL=0}{TOTAL=TOTAL+$2}END{print TOTAL}’
  #   - name: "Show each of the programs"
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace      
  #       sudo sa -a
 

  # ubuntu-1804-job:
  #   name: "process accounting  on ubuntu-18.04"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status  
  #   - name: "Install process accounting "
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace
  #       echo "=============process accounting on Linux=============="
  #       sudo apt-get update -qq
  #       sudo apt-get install acct -qqy
  #       whoami #runner
  #       sudo sa -m # averages for the all the activity for this server overtime        
  #       # sudo /usr/sbin/accton on
  #       # sudo dump-acct /var/log/account/pacct | tail
  #   - name: "Show averages for the all the activity for this server overtime"
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace      
  #       sudo sa -m # averages for the all the activity for this server overtime        
  #   - name: "Show  sum of the system and user time in cpu minutes for specific commands"
  #     run: |
  #       # set -o errexit
  #       # set -o pipefail
  #       # set -o nounset
  #       # set -o xtrace      
  #       sudo sa -u | grep runner # averages for the all the activity for this server overtime        
  #       #combined total for a specific user
  #       #sudo sa -u |grep username|awk ‘BEGIN{TOTAL=0}{TOTAL=TOTAL+$2}END{print TOTAL}’
  #   - name: "Show each of the programs"
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace      
  #       sudo sa -a

  # ubuntu-2004-job:
  #   name: "process accounting on ubuntu-20.04"
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: "os fingerprinting"
  #     run: hostnamectl status 
  #   - name: "Install process accounting "
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace
  #       echo "=============process accounting on Linux=============="
  #       sudo apt-get update -qq
  #       sudo apt-get install acct -qqy
  #       whoami #runner
  #       sudo sa -m # averages for the all the activity for this server overtime        
  #       # sudo /usr/sbin/accton on
  #       # sudo dump-acct /var/log/account/pacct | tail
  #   - name: "Show averages for the all the activity for this server overtime"
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace      
  #       sudo sa -m # averages for the all the activity for this server overtime        
  #   - name: "Show  sum of the system and user time in cpu minutes for specific commands"
  #     run: |
  #       # set -o errexit
  #       # set -o pipefail
  #       # set -o nounset
  #       # set -o xtrace      
  #       sudo sa -u | grep runner # averages for the all the activity for this server overtime        
  #       #combined total for a specific user
  #       #sudo sa -u |grep username|awk ‘BEGIN{TOTAL=0}{TOTAL=TOTAL+$2}END{print TOTAL}’
  #   - name: "Show each of the programs"
  #     run: |
  #       set -o errexit
  #       set -o pipefail
  #       set -o nounset
  #       set -o xtrace      
  #       sudo sa -a


